name: Build and Upload Artifact
'on':
  push:
    branches:
    - main
    tags:
    - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install UV
      uses: astral-sh/setup-uv@v5
    - name: Set up environment
      run: echo 'No setup required'
    - name: Build project
      run: uv build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: project-artifact
        path: dist/
        if-no-files-found: error
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
